title: "cat-oscilloscope"
description: "cat-oscilloscope"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/cat-oscilloscope
plugins:
  - jekyll-sitemap
